# Generated by Django 3.1.1 on 2021-02-27 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210225_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pictures/'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'message', 'image')},
        ),
    ]
